### ISSUE TITLE
Group imports together

### ISSUE THREAD

**Issue by tfausak** [EdutainmentLIVE/haskell-style-guide#15]
``` hs
-- bad
import Test.Hspec

import Data.Semigroup ((<>))
import qualified Control.Exception as Exception

import Database.MongoDB as Mongo

-- good
import Data.Semigroup ((<>))
import Test.Hspec

import qualified Control.Exception as Exception
import qualified Database.MongoDB as Mongo
```

Imports should be split into two groups: unqualified and qualified. There should be a blank line between the two groups. Most files will only have the second (qualified) group.

**Comment by telser** [comment]
I actually disagree with this one. I would rather have qualified and unqualified mixed than Test specific and non-specific.

Also not  sure if the wording is meant to imply that there are *only* two groups. In particular I much like what we've done with external/internal imports being grouped separately. Which can make it easier to tell where to look for something, like if you have a `DB.MongoDB.Connection` that is a project internal module mixed with the `Database.MongoDB` one here.

**Comment by telser** [comment]
I realize that they don't have anything to do with tests as written. But that is a common pattern and one that I'd prefer.  That is mixed qualified/unqualified and unmixed test/not test. 

RE the parties, yes it was done that way for a bit, but everyone that I've asked so far agreed that the first two of those groups should be merged.

In addition saying that there should ever only be two groupings seems pretty strong and hard to generalize IMO. Keeping the groups down and ideally at one or two I agree with, but I imagine someone would have a rational argument for 3. 

Lastly, it is probably more important that there is _some_ delineation that the team for project foo socializes internally than _all_ projects using the same delineation

**Comment by tfausak** [comment]
I'm not sure I understand the value of splitting up the import groups. What information is being conveyed? 

My goal is to reduce the friction of adding an import. It's nice to add it to the clump of imports, let `hindent` do its thing, and keep moving. I don't like the additional step of trying to figure out which group the module belongs to.

**Comment by telser** [comment]
It is a bit funny to me because I feel our usual roles are reversed. Here I am favoring verbosity for readability, whereas in many places we've talked about previously, you've been more in favor of that.

Specifically, have the internal/external split has helped some of the more-green-to-Haskell developers realizing where to go for information about a given imported item. At least that is what I've noticed during pairing and conversations. FWIW, I find that distinction helpful as well, without needing an extra module layer for everything. And with a similar cognitive overhead when writing/adding.

So while I agree that splitting on qualified or not is aesthetically more pleasing, in my observation it is less helpful than splitting on internal or not.

^All of the above ignores my previous comments on test specific modules, that is a slight personal preference, but not something I find worth focusing on here.

**Comment by tfausak** [comment]
Y'all have convinced me to split imports into third-party and first-party. Anything currently in the second-party group should be rounded up into third-party. Unqualified and explicit imports shouldn't get any special treatment. 

"First-party" code is basically anything that's not on Stackage.
