### ISSUE TITLE
Avoid unnecessary eta reduction

### ISSUE THREAD

**Issue by tfausak** [EdutainmentLIVE/haskell-style-guide#21]
In other words: Avoid golfing code via point free expressions.

``` hs
-- bad
((. f) . compare .)

-- good
\x y -> compare (f x) (f y)
```

In general, top level declarations should list all of their arguments. Regular expressions can avoid listing their arguments if they're simple, like operator sections. Any time you have to reach for `flip`, `fmap fmap`, or [pointfree.io](http://pointfree.io), you should probably stop and use a lambda instead. 

https://wiki.haskell.org/Pointfree

**Comment by telser** [comment]
Oy, that is a rough example! 

The recommendation of listing all arguments on the top level is directly contradictory to hlint by the way. It will suggest removing the argument name if it is only used in the final position of the definition. And those kind of simple eta-reductions don't bother me, especially to avoid the [objective-c long names](https://github.com/Quotation/LongestCocoa) sort of thing which I often find confusing.

Clearly you can take it too far, though I would imagine that being often caught by our other recommendations like not using operators, don't use prefix versions of operators etc. Maybe not?

Oh and `fmap . fmap` is super handy for reaching two functor levels down -  that a simple lambda doesn't solve, but that isn't what you meant here right? That is to say `(fmap . fmap) fn val` seems just as clear, or better since there isn't another variable name  to be confused by as to what is going on in `fmap (\x -> fmap fn x) val`.  Seems that if you're very deep in nested functors that there might be something else needing to happen, like flattening some of that structure down (aliases don't count, even though certain libraries seem to use them frequently as so). 

Some generalish thoughts on it:
Clarity, in my opinion, is the goal. Which strikes a, non-trivial to achieve, balance between concise and verbose. Too often it seems that the golfers, and the wordy (what is the opposite of a "golfer" here?) both want to be absolutists. Sometimes code is dense but clear, it can't all take 5 seconds to understand. But also sometimes a few extra characters can really help others and future self with understanding. Said  balance is different for every person and every team, which means allowing pushback both directions can be important. Personally I'm very much willing to give on _my_ clarity for that of others given that other characteristics important to whatever section of code aren't also harmed (like opening a security hole, or negatively impacting user experience, the "obvious" stuff).

**Comment by qxjit** [comment]
I agree with the sentiment that we should not commit contortions to the code in the same of golfing to point free-end ness. On the other hand, I *do* think we should promote higher level thinking where leaving out parameters makes sense because you're actually operating mentally on the functions themselves, rather than the parameters of those functions.

In all such cases though, they resulting function should be perfectly understandable and readable. If it expressing the parameters is what makes it so, then the parameters should be expressed.

**Comment by tfausak** [comment]
> what is the opposite of a "golfer" here?

I think it's "bowler" 😄 

My wording needs to mellow out a bit. My goal here is to discourage point-free golfing for the sake of it. And the overall goal is clarity. Eta reducing expressions can make it easier to see there shape, and therefore easier to understand them. 

``` hs
-- bad
sum xs = foldr (\x y -> x + y) 0 xs

-- good
sum = foldr (+) 0
```
