### ISSUE TITLE
Always derive at least Eq and Show

### ISSUE THREAD

**Issue by tfausak** [EdutainmentLIVE/haskell-style-guide#23]
``` hs
-- bad
data Switch = Off | On

-- good
data Switch = Off | On deriving (Eq, Show)
```

To make debugging easier, every data type should derive the `Eq` and `Show` type classes. Other type class instances, like `Ord` and `Read`, are up to your discretion.

**Comment by telser** [comment]
If you're debugging where adding something to the code to be output, the compiler will yell about not having `Eq` or `Show` and since they are so trivial to add, it doesn't seem like that much of a burden. 

That goes out the window if you're attaching to a running system and asking it to print/equality test/etc something that it doesn't normally, a la Erlang(or I guess really the BEAM). I know there are people out there doing _some_ of the more Erlang type stuff like hot reload, but can we even do the above?

Lastly, assuming that we can't do that, is it worth it to do the small amount of work, that might never be needed, ahead of time as opposed to just-in-time?

**Comment by telser** [comment]
Oh and my previous comment is almost always moot since it is so common to need something more than those two defaults and we often end up deriving them anyway.
Ack! Also, `Read` can go sideways pretty quick so we may not want to mention that one. For example, requiring record fields be in the same order. [ref](http://hackage.haskell.org/package/base-4.11.1.0/docs/Text-Read.html#t:Read)

**Comment by tfausak** [comment]
Adding `Eq` and `Show` when you need them isn't too much of a hassle, but I hate it when I add `print something` to a function and spent the next 5 minutes chasing down "no instance for `Show t`" errors throughout the code base. Then when I'm done, should I remove all the instances I added? 

In general we should avoid deriving stuff we don't need, but `Eq` and `Show` are useful for both debugging and testing, which are things we do frequently. Also they're the fastest type classes to derive ([source](https://taylor.fausak.me/2017/08/09/deriving-type-classes-in-haskell-is-slow/)).

**Comment by tfausak** [comment]
To reiterate, `Eq` and `Show` are the fastest type classes to derive:

![](https://taylor.fausak.me/static/images/2017/08/09/deriving-performance.svg)

I'm willing to pay that price. 

There are some types that shouldn't have `Show` instances. For example, anything sensitive like passwords.

``` hs
newtype Password
  = Password Text
  -- doesn't derive `Show` to avoid accidentally printing it out
```

You could manually provide an instance that hides the sensitive information:

``` hs
showPassword :: Password -> Text
showPassword _ = "Password \"[REDACTED]\""

instance Show Password where
  show = showPassword
```

That would also prevent future developers from accidentally adding `deriving Show`.
